### PR TITLE
Vu/remove email verification

### LINKED ISSUE #666: Remove email verification step during customer onboarding
[Per this proposal, ](https://docs.google.com/document/d/1AKHfHJIKKs4sKcNqw8s3YYPfCO-qqf0DFhvo1Io8CS8/edit#) I'd like to remove the step where customers are required to verify their email before being dropped into the dashboard. 

Requirements:
- Customers should use the registration page to sign up for an account
- Customer information is automatically saved into Hubspot (as they are today) 
- Verification email is still sent, although it is not required to access the account
- Copy on the verification email needs to be changed (details below) 
- Once customer signs up for an account, they are immediately directed to the dashboard (elimination of the screen that requires verification) 
- IMPORTANT: we will need to be able to easily and quickly roll back these changes. 

## Customer Experience: 

1. User registers at Livepeer.com/register (no change) 

2. Customer account is created and immediately dropped into an account. 
Change: removal of the verification step

3. Customer is sent a verification email to email on file, although there is no incentive to verify 

Copy is changed to: Please verify your email address to ensure that you can change your password or receive updates from us.

### PR DESCRIPTION
**Pull request by FullStackTiger**
**What does this pull request do? Explain your changes. (required)**

**Specific updates (required)**

 - Remove email verification step during customer onboarding

**Does this pull request close any open issues?**

- Fixes #666

**Screenshots (optional):**

**Checklist:**

- [ ] I have read the **CONTRIBUTING** document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by adamsoffer** [comment]
@FullStackTiger this looks good but let's first figure out spam prevention before merging. https://github.com/livepeer/livepeer-com/issues/666#issuecomment-961229596

**Comment by FullStackTiger** [comment]
Yes!, it doesn't have spam prevention.
I think we should add some validations for all of the fields(firstName, lastName, organization, phone, email, password) first.
@adamsoffer

**Review by iameli — DISMISSED** [review]
Can we make enabling/disabling verification on the front-end into a constant that we could import to make it easier if we ever want to flip this back on?

**Comment by FullStackTiger** [comment]
> Can we make enabling/disabling verification on the front-end into a constant that we could import to make it easier if we ever want to flip this back on?

I added enabling/disabling verification function on the front-end with NEXT_PUBLIC_EMAIL_VERIFICATION_MODE env var

**Review by adamsoffer — APPROVED** [review]
LGTM!

**Pull request merged**
