### PR TITLE
Update nav "Use Cases" to "Products" and rearrange

### PR DESCRIPTION
**Pull request by FullStackTiger**
**What does this pull request do? Explain your changes. (required)**

**Specific updates (required)**

## Update nav "Use Cases" to "Products" and rearrange

**Does this pull request close any open issues?**

- Fixes #[Update nav "Use Cases" to "Products" and rearrange](https://app.zenhub.com/workspaces/video-user-team-5dd2c75e4ee08500015994d7/issues/livepeer/internal-project-tracking/312)

**Screenshots (optional):**

**Checklist:**

- [ ] I have read the **CONTRIBUTING** document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Review by MRTIBBETS — APPROVED** [review]
The copy updates look good. I can't speak for the code, but I look forward to seeing how this is live. :)

**Comment by adamsoffer** [comment]
Screen Shot 2022-02-05 at 10 16 29 AM

Each product category should have a unique icon - can we find a distinct one for Media Server? 

Also, this products dropdown makes it appear like we offer streaming services for creators, gamers, and musicians when in fact we offer a development platform for developers to build streaming platforms that can serve creators, gamers, and musicians. People confuse Livepeer as a twitch alternative and this feels like this change only reenforces that misconception. How can we get across the message that this is a video development platform for developers?

Also, are we comfortable linking out to mistserver.org in the dropdown or do we want to wait until we have a proper landing page at /media-server? Strongly prefer the later. Mistserver.org is off-brand and has its own sign up system / portal and separate licensing agreements and everything. Feels super confusing to me as a developer / user of the Livepeer Video Services.

@MRTIBBETS your call if you still want to merge, but I want to raise these flags beforehand.

**Comment by MRTIBBETS** [comment]
Thank you, Adam, for this! I shared IRL and will here too... this is _definitely_ an iteration and a start for tweaking this experience to something better.

It is indeed not ideal, but I hope to iterate to something better and more useful than we have now then deploy BUILT to help us rethink these systems and tools.

For the landing page, I actually have a new ticket specific to creating just that for MistServer here: https://app.zenhub.com/workspaces/product--commercial-product-tracking-5fd7c74c7260fd0011aaff58/issues/livepeer/internal-project-tracking/325

That's cooking up next!

**Comment by MRTIBBETS** [comment]
@FullStackTiger The latest tickets I'm creating for you take this work to one level further iteration, so you might consider merging on to a branch that we'll be editing on for Friday and into the weekend before deploying.

**Comment by FullStackTiger** [comment]
A New Product landing page(Media Server) was created on another https://github.com/livepeer/livepeer-com/pull/901, so updated the link to /products/media-server, also updated the icon like this
image

@MRTIBBETS @adamsoffer

**Review by adamsoffer — APPROVED** [review]
LGTM

**Pull request merged**
