### PR TITLE
Link to Dashboard at top of Livepeer.com/docs

### LINKED ISSUE #731: Link to Dashboard at top of Livepeer.com/docs
As a user on the dashboard, if I click on a link to the docs, there's no easy way for me to navigate back to the dashboard. 

To address this, please add a link to https://livepeer.com/dashboard at the top navigation of Livepeer.com/docs, like this:

### PR DESCRIPTION
**Pull request by FullStackTiger**
**What does this pull request do? Explain your changes. (required)**

**Specific updates (required)**

- Link to Dashboard at top of Livepeer.com/docs

**Does this pull request close any open issues?**

- Fixes #731 

**Screenshots (optional):**

**Checklist:**

- [ ] I have read the **CONTRIBUTING** document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Review by pglowacky — APPROVED** [review]

**Review by adamsoffer — CHANGES_REQUESTED** [review]
@FullStackTiger can we use the primary button link style like we do on the marketing pages?

image

**Comment by FullStackTiger** [comment]
@adamsoffer  good idea, but it is not good the button position on the mobile view like this:
image

**Comment by pglowacky** [comment]
I'm +1 to dropping the styling to improve the mobile view

**Review by adamsoffer — APPROVED** [review]
LGTM!

**Pull request merged**
