### PR TITLE
Test player redesign

### LINKED ISSUE #266: Build ingest rate into Livepeer.com test player

### PR DESCRIPTION
**Pull request by emilianoyaryura**
**What does this pull request do? Explain your changes. (required)**

UI Implementation of the test player redesign

**Specific updates (required)**

- Redesign of the test player
- New JSONHighlighter

**How did you test each of these updates (required)**

- Desktop, tablet and mobile. 
- https://mdw-cdn.livepeer.monster/hls/c47dk0tx0hkz4xei/index.m3u8  (playback URL)

**Does this pull request close any open issues?**

- closes #266

**Screenshots (optional):**

Screen Shot 2021-02-22 at 18 33 19
Screen Shot 2021-02-22 at 18 33 33
Screen Shot 2021-02-22 at 18 33 49
Screen Shot 2021-02-22 at 18 34 04
Screen Shot 2021-02-22 at 18 34 13

**Checklist:**

- [x] I have read the **CONTRIBUTING** document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.

### CODE REVIEW

**Comment by wohlner** [comment]
@adamsoffer, @Emiliano0308 is building out a revised test player. He messaged me in slack that "regarding the stream info, we couldn't retrieve that data, it throws a 'Not found' error. Do you have any ideas why this could be?". Is this expected in development? Do they need to be running something else locally to better test?

**Comment by adamsoffer** [comment]
@Emiliano0308 - this looks great! One minor piece of feedback from my end is I noticed "stream not found" flickers when pasting a url before the check mark eventually appears. Can we fix that?

**Review by wohlner — CHANGES_REQUESTED** [review]
Change your please change the video headers? Change `Source` to `Your source stream only` and change `ABR` to `Source stream + Livpeeer.com transcoded renditions` Also change the left subheader from `highest resolution only` to `Only the source is streaming.`, and change the right subheader from `Source stream + transcoded renditions` to `Adaptive bitrate streaming`

**Comment by wohlner** [comment]
Also under `ie. https://fra-cdn.livepeer.com/hls/123456abcdef7890/index.m3u8` please add a line in the same font treatment `Stream playback will work in all browsers and devices, but this test player tool works best in Chrome.`

**Comment by wohlner** [comment]
Please make livepeer.com not a link 
Screen Shot 2021-03-02 at 2 50 11 PM

Once that change happens, this lgtm :)

**Comment by wohlner** [comment]
And change the X axis label from `sec` to `Seconds since stream loaded in test player`

**Comment by wohlner** [comment]
This looks wonderful! Great work. No further changes requested. I am going to share this preview link with our customer success lead.

**Review by wohlner — CHANGES_REQUESTED** [review]
A couple comments on the ingest rate chart after getting feedback from some livepeer co-workers.

1. The session ingest rate should be on a "fixed" Y axis from 0kbps to 10000kbps.  Currently it dynamically changes depends on the value, making it feel like the ingest rate dramatically flucuates. 
2. Let's change the Y axis label to `kbps`
3. Please change the session ingest rate to be a "growing" X axis from 0.  Currently it rolls off, keeping around 60 seconds "in view".

**Comment by wohlner** [comment]
Please change the Y axis label to `1000 kbps`.

And it looks like there is a lil bug: once the first ingest rate number comes in the Y axis starts at a negative number. It should stay at zero.
Screen Shot 2021-03-03 at 10 18 38 AM
Screen Shot 2021-03-03 at 10 18 28 AM

**Review by wohlner — APPROVED** [review]

**Pull request merged**
