### PR TITLE
Adding streaming credits application in the footer

### PR DESCRIPTION
**Pull request by ericxtang**
**What does this pull request do? Explain your changes. (required)**
Adds the streaming credits application to the footer

**Specific updates (required)**
A link in the footer

**How did you test each of these updates (required)**
Just copied the last link block

**Does this pull request close any open issues?**

**Screenshots (optional)**

**Checklist**

- [ ] I have read the **CONTRIBUTING** document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by ericxtang** [comment]
umm... I'm not sure what to do now... the change was very simple - just adding a static link to a page.

**Comment by adamsoffer** [comment]
@ericxtang weird, I'll have a look

**Review by 0xcadams — APPROVED** [review]

**Comment by 0xcadams** [comment]
Okay so this is now deploying - but where do we want this added? I don't see the footer on the landing page, or on the authorized pages. cc @ericxtang

**Comment by adamsoffer** [comment]
@ericxtang I was hoping to deploy #1680 this week which includes a link to the streaming credit application in the footer of the [new landing page](https://livepeer-studio-git-as-theme-update-livepeer.vercel.app/). Shall we close this PR in favor of that one?

**Pull request closed without merging**
