### PR TITLE
Usage API endpoint and admin page

### LINKED ISSUE #78: sourceSecondsDuration endpoint
For any given account, we need an endpoint to query the `sourceSecondsDuration` for all streams created thus far in an active billing cycle and at the end of the billing cycle.

`sourceSecondsDuration` for the active billing cycle will be displayed on the usage tracking page in the livepeer.com admin and must be updated at least daily.  `sourceSecondsDuration` will also be used at the end of the billing cycle for billing via our Stripe integration. To get an accurate count, we will need to query for streams with a parent id for a given account.

The billing cycle is not the first of the calendar month to the end of the calendar month. The billing cycle should be able to be set arbitrarily.

### PR DESCRIPTION
**Pull request by darkdarkdragon**
**What does this pull request do? Explain your changes. (required)**
/user/usage endpoint - returns usage data for the user in the specified time interval

**Specific updates (required)**

## -

-

**How did you test each of these updates (required)**

**Does this pull request close any open issues?**
Fixes #78 

**Screenshots (optional):**
image

**Checklist:**

- [ ] I have read the **CONTRIBUTING** document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by wohlner** [comment]
The Usage page UI is helpful for reviewing what is available with the endpoint, but @adamsoffer will create a differently designed one based on the user's billing cycle dates. @adamsoffer your call if you want to keep the UI in the PR. 

This is super helpful, @darkdarkdragon, thanks!

**Comment by adamsoffer** [comment]
Thanks @darkdarkdragon !

@wohlner I see the UI introduced in this PR is for the admin page; it doesn't interfere with the usage page I already implemented which is user facing and would be a nice internal tool for us to look up a user's usage for a given time period so I'm inclined to keep it.

**Review by adamsoffer — CHANGES_REQUESTED** [review]
@darkdarkdragon good to merge once we fix this type error causing the build fail.

```
Type error: Argument of type 'Error \| User[]' is not assignable to parameter of type 'SetStateAction<any[]>'.
Type 'Error' is not assignable to type 'SetStateAction<any[]>'.
Type 'Error' is missing the following properties from type 'any[]': length, pop, push, concat, and 28 more.
```

**Comment by darkdarkdragon** [comment]
@adamsoffer fixed

**Pull request merged**
