### PR TITLE
Emi/pricing

### PR DESCRIPTION
**Pull request by emilianoyaryura**
**What does this pull request do? Explain your changes. (required)**
New pricing page.

**Specific updates (required)**

## -

- **How did you test each of these updates (required)**

**Does this pull request close any open issues?**

**Screenshots (optional):**

**Checklist:**

- [ ] I have read the **CONTRIBUTING** document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by wohlner** [comment]
Overall, this looks great and seems to work well. 

Here is how to calculate the CDN:
The price is $0.01 per GB for streaming via CDN
We have to convert the number of viewers, streams, length into GB to get this number.
We will assume the estimated average bit-rate delivered is 10000 (average Kbps)

The cost of streaming via CDN per month = (60 x average length of streams in minutes x number of monthly live streams x average Kbps) ÷ 8 ÷ 1024 ÷ 1024) x monthly live stream view count x percent of stream watched x $0.01

**Comment by wohlner** [comment]
Please change the calculation above by changing the average kbps value to 2000

**Review by adamsoffer — CHANGES_REQUESTED** [review]
Hey @emilianoyaryura. Chiming in here on a couple design elements. 

1. On mobile can we add pagination dots below the slider? It is not obvious you can swipe. Either that or simply stack the cards similar top what Vercel.com/pricing does on their pricing page.
image

2. Can you please change this text color to black? Purple should mostly be reserved for hyperlinks. Thanks!

image

**Comment by wohlner** [comment]
This looks great. Tiny typo: please change all instance of "comming" to "coming."

**Comment by adamsoffer** [comment]
Hey @emilianoyaryura - looks like this is just about ready to merge. The one thing I noticed is the "Get Started" and "Contact Us" call to actions are missing links. Can you address? Thanks.
image
image

**Comment by adamsoffer** [comment]
@emilianoyaryura LGTM!

**Pull request merged**
