### PR TITLE
feat: add VOD detail page

### LINKED ISSUE #1024: VOD Dashboard UI: Creation Flow
https://www.figma.com/file/o0lkaZxamhUfG6eqSglhPO/Livepeer-VOD-Asset-Dashboard?node-id=51%3A1789

### LINKED ISSUE #1026: Asset List Page Changes
https://www.figma.com/file/o0lkaZxamhUfG6eqSglhPO/Livepeer-VOD-Asset-Dashboard?node-id=51%3A1789

### LINKED ISSUE #1027: Asset Detail Page
https://www.figma.com/file/o0lkaZxamhUfG6eqSglhPO/Livepeer-VOD-Asset-Dashboard?node-id=51%3A1789

### LINKED ISSUE #1028: Edit Asset on the Asset Detail Page
https://www.figma.com/file/o0lkaZxamhUfG6eqSglhPO/Livepeer-VOD-Asset-Dashboard?node-id=51%3A1789

### PR DESCRIPTION
**Pull request by 0xcadams**
**What does this pull request do? Explain your changes. (required)**

Adds VOD detail page.

**Does this pull request close any open issues?**

Fixes #1026 
Fixes #1027 
Fixes #1028 
Closes https://github.com/livepeer/studio/issues/1024

### CODE REVIEW

**Review by adamsoffer — CHANGES_REQUESTED** [review]
Looks fantastic. Just a few minor change requests.

- [x] Let's remove the "ready" badge once a video is done uploaded. That badge should only appear if an upload is processing.
image

- [x] Let's bump up the size of this "Edit Asset" button one unit to match the others 

image

- [x] Add an max width + ellipsis to asset title 

image

**Comment by victorges** [comment]
Really nice! From testing the UI:
 - The bitrate seems to always be showing `0.00`. Does it happen on your assets as well? If yes, maybe we have a bug in the pipeline that is not populating this and we should probably remove it from the frontend as well until that works.
 - The edit asset metadata field has an example object that is incompatible with the schema since it only supports `string` values right now. Could make the `tokenId` property value by a string version `"316"` (can reevaluate schema as well) 
Screen Shot 2022-08-16 at 21 05 23
 - When an asset is not on IPFS yet, there's a button saying "Upload to IPFS". I'd refrain from using the `Upload` word here not to be confused with the "upload" term for creating new assets. WDYT of `Save to IPFS`?

**Comment by victorges** [comment]
> The bitrate seems to always be showing 0.00. Does it happen on your assets as well? If yes, maybe we have a bug in the pipeline that is not populating this and we should probably remove it from the frontend as well until that works.

Ah I found what it is! After [#1154](https://github.com/livepeer/studio/pull/1154/files#diff-ed7a14d016bf3f1e0d94b5823604fde2f1dba33ce1376c00c1237dfa3ed3775bR272), we started hiding some details info from the `asset` object by default unless requested (not for admins tho). This includes the `tracks` field inside the `videoSpec` which has info about the video, where you take the bitrate and resolution from.

So to fix this, you need to add `?details=1` query-string to the API where you get the asset details to show in the page. Value can be anything actually, we only check if it is a truthy string (can be improved).

**Comment by 0xcadams** [comment]
Moving TODOs from https://github.com/livepeer/studio/pull/1194 to this PR since this is a superset of it:

- [x] Make warning on upload snackbar yellow/orange instead of a red
- [x] Add warning while trying to close the tab when uploading

**Comment by 0xcadams** [comment]
@adamsoffer @victorges @iameli thanks for the review, made those changes requested

**Review by adamsoffer — APPROVED** [review]
Looks great! Just noticed on light mode the close button on the snackbar should be black. Other then that, good to merge.
image

**Pull request merged**
