### PR TITLE
Add filtering and pagination to the Admin Users page

### PR DESCRIPTION
**Pull request by darkdarkdragon**
**What does this pull request do? Explain your changes. (required)**
Add filtering and pagination to the Admin Users page	

**Screenshots (optional):**

image

Update:
Added ability to filter users by their payment plan
image

### CODE REVIEW

**Comment by wohlner** [comment]
I did not mean to close this. SORRY!

**Comment by wohlner** [comment]
Awesome initiative on this! I am unable to test the previous and next buttons because there are less than 101 streams.

I tested the filter field, and when I type in "jen" i get way more results than expected, many that don't make sense. I would expect the results to be only `id`s and `emails` that contain `jen`. 

Screen Shot 2020-12-17 at 1 40 37 PM

**Comment by wohlner** [comment]
Now I see that the preview text in the text field where I can filter says "email." But still I was getting back unexpected results besides emails that contain the string `jen`

**Comment by darkdarkdragon** [comment]
@wohlner you won't be able to see it working correctly until it is deployed to staging - you're testing only frontend part, but filtering is done on backend which is not gets deployed to the Vercel's test deployment.

**Comment by wohlner** [comment]
The "Show Livepeer's users" is confusing and takes up super valuable real estate above the table. 

Please change it to "Exclude users with a Livepeer email address" and this should only return users without @livepeer.com or @livepeer.org email addresses. This should be unchecked by default.

**Comment by darkdarkdragon** [comment]
@wohlner 
> "Exclude users with a Livepeer email address"

This takes even more space 😃 
And what's the point - we have not that many Livepeer users? 
Initially I've added 'Show Livepeer's users only' when there was no filtering yet so it can be possible to find Livepeer user and make that user to be admin. But with filtering it's that important (though probably it's still good to have list of only Livepeer users - just to have overview).

**Comment by wohlner** [comment]
Well, to get all LP users, we could just filter for "livepeer" and all the users with livepeer.com and .org email addresses would show up. How about you just remove that checkbox and not replace it with anything. 👍

**Pull request merged**
