### PR TITLE
Minor changes to pricing page for CDN Usage

### LINKED ISSUE #657: Minor changes to pricing page for CDN Usage
Two changes:
1. Remove the asterisk
2. Change asterisk copy to:

_Currently, we are not charging for this feature. We'll be sure to reach out before we do._

### PR DESCRIPTION
**Pull request by FullStackTiger**
**What does this pull request do? Explain your changes. (required)**

**Specific updates (required)**

## - Minor changes to pricing page for CDN Usage

- Remove the asterisk
- Change asterisk copy to(both of pages: pricing and dashboard plans pages):
Currently, we are not charging for this feature. We'll be sure to reach out before we do.
- Change the pricing to new CDN pricing: $0.015/GB

**Does this pull request close any open issues?**

- Fixes #657 

**Screenshots (optional):**

**Checklist:**

- [ ] I have read the **CONTRIBUTING** document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Review by adamsoffer — CHANGES_REQUESTED** [review]
Make sure to also update the CDN pricing on the dashboard plans view at `/dashboard/billing/plans` from $0.02 to $0.015

**Comment by pglowacky** [comment]
> Make sure to also update the CDN pricing on the dashboard plans view at `/dashboard/billing/plans` from $0.02 to $0.015

I believe that we decided to keep it how it was listed. I'll confirm with Alexander, but please do not change it to $0.015 for now.

**Comment by pglowacky** [comment]
Hey folks -- @MRTIBBETS is going to get back to us with final pricing, please hold off on deploying this until we confirm pricing.

**Comment by pglowacky** [comment]
@FullStackTiger we're moving forward with $0.015/GB, so feel free to make these changes. 

(I think I followed up with you elsewhere, just confirming here)

**Comment by FullStackTiger** [comment]
> @FullStackTiger we're moving forward with $0.015/GB, so feel free to make these changes.
> 
> (I think I followed up with you elsewhere, just confirming here)

ok, I will merge it

**Comment by pglowacky** [comment]
Still seeing this:

**Comment by FullStackTiger** [comment]
it is not deployed to the production yet

**Pull request merged**
