### PR TITLE
Rewrote much of the docs

### PR DESCRIPTION
**Pull request by wohlner**
I rewrote much of the docs copy and made each section flow step by step.

I needs a lil help finalize the formatting though. 

1. Next to the new account section in the menu, we need an icon.
1. It's kind of awkward that all menu sections open when you refresh the page
1. I'd like to see what the options are for the basement designed docs hub.

### CODE REVIEW

**Comment by wohlner** [comment]
@adamsoffer can you please make the following changes?:

- an icon next to "Your Livepeer Account on /docs/guides"
- the menu on /docs/guides is really long with all the menu items open. Is there a way to remember the user's menu state as they navigate between pages? Or can you just make the menu much small font so it all fits?

**Comment by adamsoffer** [comment]
@wohlner I've added an icon to the account guide and collapsed the menu items unless active so it's not so long.

**Comment by adamsoffer** [comment]
@wohlner I've replaced the purple icons with more appropriate ones provided by basement. They're pretty rad.

**Comment by wohlner** [comment]
OMG, the new icons are perfect. Can you deploy this to stage today so we can more easily share it with the rest of the team?

**Comment by adamsoffer** [comment]
:) I can merge into master. Note that `livepeer.monster` is currently set up to point to my billing branch so it won't automatically deploy there, but we can share out this preview url with the team instead.

**Comment by wohlner** [comment]
Good call, I'll share this vercel preview link

**Comment by adamsoffer** [comment]
@wohlner I pushed up another fix for the link bug. Can you visit this preview url, hard refresh, and let me know if you can reproduce? https://livepeer-com-git-rewrite-docs.livepeerorg.vercel.app

**Comment by wohlner** [comment]
@adamsoffer all fixed! I tested in a chrome incognito tab. These are ready for production now.

**Pull request merged**
