### PR TITLE
bump livekit, figure out axios problems

### PR DESCRIPTION
**Pull request by iameli**
* Bumps livekit.
* Adds a failing test for when it doesn't work in the Docker build

### CODE REVIEW

**Review by victorges — APPROVED** [review]
LGTM tho not sure what is different here that fixed the livekit+axios stuff. Was it only the image problem in livepeer-infra after all?

**Comment by victorges** [comment]
Ah cool, got it, it didn't get fixed yet 🤔 
```
#18 [stage-1 4/4] RUN /usr/local/bin/livepeer-api --help
#18 3.834 Error: Cannot find module '/snapshot/app/node_modules/livekit-server-sdk/node_modules/axios/dist/node/axios.cjs'
#18 3.834 1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
#18 3.834     at createEsmNotFoundErr (node:internal/modules/cjs/loader:967:15)
#18 3.834     at finalizeEsmResolution (node:internal/modules/cjs/loader:960:15)
#18 3.834     at resolveExports (node:internal/modules/cjs/loader:488:14)
#18 3.834     at Function.Module._findPath (node:internal/modules/cjs/loader:528:31)
#18 3.834     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:932:27)
#18 3.834     at Function._resolveFilename (pkg/prelude/bootstrap.js:1951:46)
#18 3.834     at Function.Module._load (node:internal/modules/cjs/loader:787:27)
#18 3.834     at Module.require (node:internal/modules/cjs/loader:1012:19)
#18 3.834     at Module.require (pkg/prelude/bootstrap.js:1851:31)
#18 3.834     at require (node:internal/modules/cjs/helpers:102:18)
#18 ERROR: process "/bin/sh -c /usr/local/bin/livepeer-api --help" did not complete successfully: exit code: 1
```

**Comment by iameli** [comment]
@victorges Yeah, I think this fixes f57e8ee6bea10c7820b8c6a25912ced255654a52

**Comment by victorges** [comment]
@iameli cool! 🚀

**Pull request merged**
