### PR TITLE
Add 404 page

### LINKED ISSUE #115: 404 page for livepeer.com
We need one!

### PR DESCRIPTION
**Pull request by arzafran**
**What does this pull request do? Explain your changes. (required)**

**Specific updates (required)**

- Added the DefaultError component to be used in any case a SSR generated template needs to display a 404

**How did you test each of these updates (required)**

Tested on macOS Big Sur:
- Safari
- Brave
- Firefox

**Does this pull request close any open issues?**

Fixes #115

### CODE REVIEW

**Comment by wohlner** [comment]
In the Vercel preview in Chrome, the "go to the homepage" button doesn't work.

**Comment by wohlner** [comment]
LGTM

**Comment by wohlner** [comment]
@darkdarkdragon can you please review and take the necessary steps to deploy to production?

**Comment by darkdarkdragon** [comment]
@wohlner deployed to livepeer.com

**Pull request merged**
