### PR TITLE
Issue 644 - Sizing of Webhooks Page

### LINKED ISSUE #644: Sizing of Webhooks Page
"Update details" hangs over the edge of the container on the front end. I would expect these elements to stack on top of each other if the window isn't big enough

### PR DESCRIPTION
**Pull request by FullStackTiger**
**What does this pull request do? Explain your changes. (required)**

Sizing of Webhooks Page #644

**Specific updates (required)**

- **fixed buttons position issue on Webhooks Page**

- **How did you test each of these updates (required)**

**Does this pull request close any open issues?**

- **Fixes #644**

**Screenshots (optional):**

**Checklist:**

- [ ] I have read the **CONTRIBUTING** document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Review by adamsoffer — CHANGES_REQUESTED** [review]
@FullStackTiger rather than stacking can we simply truncate the title in the header with an ellipsis if it's greater than a certain amount of characters? You can use the already installed dependency [`react-text-truncate`](https://www.npmjs.com/package/react-text-truncate).

**Comment by FullStackTiger** [comment]
Yes! displayed the title in the header with an ellipsis if it's greater than a certain amount of characters

**Review by adamsoffer — APPROVED** [review]
LGTM 🛳

**Comment by adamsoffer** [comment]
Nice use of `text-overflow` btw :)

**Pull request merged**
