### PR TITLE
Reveal global ingest and playback URLs in UI

### LINKED ISSUE #346: Global ingest/playback URLs on Livepeer.com Dashboard stream page
Add new global RTMP ingest and playback URL pairs and hide the regional ones:

Display the regional url pairs. The purple text should link to https://livepeer.com/docs/guides/dashboard/ingest-playback-url-pair. The docs copy will be updated.

### PR DESCRIPTION
**Pull request by darkdarkdragon**
**What does this pull request do? Explain your changes. (required)**
Reveal global ingest and playback URLs in UI

**Does this pull request close any open issues?**
fixes #346

**Screenshots (optional):**

image

image

### CODE REVIEW

**Comment by darkdarkdragon** [comment]
@wohlner need somewhere to point `Learn more about forgoing` url 😄 Otherwise it is done.

**Review by wohlner — CHANGES_REQUESTED** [review]
Hey @darkdarkdragon, this looks great! A couple changes though:

- Please make the "> Regional ingest and playback URL pairs" the same font as "Playback URL" above. It should NOT have the font treatment of a heading. See the images on https://app.zenhub.com/workspaces/video-user-team-5dd2c75e4ee08500015994d7/issues/livepeer/livepeer-com/346 for an estimate of how the font should be treated and how to space the rows before section is expanded.
- Remove the stream key from the regional ingest URLs
- The purple text should link to https://livepeer.com/docs/guides/dashboard/ingest-playback-url-pair. The docs copy will be updated.

**Comment by darkdarkdragon** [comment]
@wohlner 

image

----
image

**Comment by wohlner** [comment]
Looks perfect

**Pull request merged**
