### PR TITLE
Add page to Dashboard for "Media Server" under Developers

### PR DESCRIPTION
**Pull request by FullStackTiger**
**What does this pull request do? Explain your changes. (required)**

**Specific updates (required)**

## Add page to Dashboard for "Media Server" under Developers

- **How did you test each of these updates (required)**

**Does this pull request close any open issues?**

- Fixes [Add page to Dashboard for "Media Server" under Developers](https://app.zenhub.com/workspaces/video-user-team-5dd2c75e4ee08500015994d7/issues/livepeer/internal-project-tracking/311)

**Screenshots (optional):**

**Checklist:**

- [ ] I have read the **CONTRIBUTING** document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Review by MRTIBBETS — CHANGES_REQUESTED** [review]
Can you update `Livepeer Media Server (Mist)` to `Livepeer Media Server (MistServer)` please? 

Thanks in advance!

**Comment by FullStackTiger** [comment]
> `Livepeer Media Server (Mist)` to `Livepeer Media Server (MistServer)`

Updated

**Review by MRTIBBETS — APPROVED** [review]

**Comment by MRTIBBETS** [comment]
Note for Adam: another iterative update. With potential to tweak the copy and framing after deploy.

**Review by adamsoffer — APPROVED** [review]
LGTM!

**Pull request merged**
