### PR TITLE
feat: added login and update livepeer.js 

### PR DESCRIPTION
**Pull request by victorges**
the comeback of #1984

### CODE REVIEW

**Comment by 0xcadams** [comment]
There were a bunch of verbiage fixes and logic fixes in the OG PR - can we bring those back?

**Comment by victorges** [comment]
@0xcadams wow that's super weird. The changes were in the branch, but github wasn't really displaying them on the diff. Apparently I missed the revert commit when I did the `merge` with master, but I did another [(empty)](https://github.com/livepeer/studio/pull/2008/commits/af146a89e29d71e1b04e846c153160d798a8337a) one and it seems to be fixed now.

Edit: Actually, it's not fixed yet. But you can see all the commits on the history here. You know what I'll just explode the branch and create from scratch from the merged changes.

**Comment by victorges** [comment]
@0xcadams ok NOW it's fixed

**Comment by 0xcadams** [comment]
> @0xcadams ok NOW it's fixed

Thanks! Reviewing now...

**Review by 0xcadams — APPROVED** [review]
LGTM!

**Review by adamsoffer — APPROVED** [review]

**Pull request merged**
