### PR TITLE
Better error management on assets upload

### LINKED ISSUE #1250: Improved task error handling on dashboard
Right now, when a upload task fails on the dashboard it shows as successful in the task bar. A user only knows there's been a problem when they go to the asset detail page and see that it's failed. There is no error messaging on this page. 

This was surfaced in a friction log by @ecmulli and has come up in conversations with users

### PR DESCRIPTION
**Pull request by clacladev**
**What does this pull request do? Explain your changes. (required)**
Add processing issues on asset list and on file upload dialog.

**Specific updates (required)**
- Added error info to the Asset table item (red name, error icon, error badge with short info and more error details in the tooltips)
- Added error info inside the File Upload dialog
- Added the ability to Delete an asset which failed to process
- Limited the files that can be uploaded to mp4

- **How did you test each of these updates (required)**
Tested on light and dark theme.

**Does this pull request close any open issues?**
Fixes #1250 

**Screenshots (optional):**
Error state for an asset entry:
Screenshot 2022-09-28 at 15 01 29

Error details on asset tooltip:
Screenshot 2022-09-28 at 18 25 45

Error info inside the File Upload:
Screenshot 2022-09-27 at 17 15 36

Delete button for failed processing assets (loading and normal state):
Screenshot 2022-09-28 at 18 28 00

File upload only allows mp4 files:
Screenshot 2022-09-28 at 18 28 54

**Checklist:**
- [ ] It needs to be tested by other team members
- [ ] The column sizes of the table are not ideal. The Delete column is occupying too much space, leaving less to the other which would need it more

### CODE REVIEW

**Review by adamsoffer — CHANGES_REQUESTED** [review]
Just tested and works great 🔥

I just have a couple styling improvements I'd like to get made before we merge.

1. Can we add some space between the first and second column? See the figma file for proper spacing.
CleanShot 2022-09-29 at 23 53 36@2x

2. Can we replace the delete icon with the radix icon trash icon (`<TrashIcon />`) and give it a margin right of `$2`? Also, the circular gray background behind the icon should only appear on hover. Can give it a slight fade in on hover (ie`transition: 0.2s`).

**Comment by clacladev** [comment]
@adamsoffer I solved both issues. So whenever you want you can re-review and merge

**Comment by adamsoffer** [comment]
Hey @clacladev - I'm trying to test this on the preview url. Do you have a file that you know will fail processing so I test on my end?

**Comment by adamsoffer** [comment]
> Hey @clacladev - I'm trying to test this on the preview url. Do you have a file that you know will fail processing so I test on my end?

Nevermind, was able to just rename a file to .mp4 to test

**Review by adamsoffer — APPROVED** [review]
Looks fantastic :)

**Pull request merged**
