### PR TITLE
recording.ready and recording.started

### PR DESCRIPTION
**Pull request by ya7ya**
**What does this pull request do? Explain your changes. (required)**

**Specific updates (required)**

## -

- **How did you test each of these updates (required)**

**Does this pull request close any open issues?**

**Screenshots (optional):**

**Checklist:**

- [ ] I have read the **CONTRIBUTING** document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Review by victorges — COMMENTED** [review]
I think the `setRecordingStatus` function is only called, and always called, on GET requests for the stream. I think that means that:
 - the recording started/ready events would only really be emitted when the users themselves actually query for the stream, in which case the event seems unnecessary (they'd already receive the status in the response)
 - the events might also be sent multiple times, every time a new GET request is made which contains the stream as a result. 

That said, I think what this function actually does is something like `addRecordingFields` instead? Not sure if I misunderstood something or missed some other place where this function is called.

And also following up on the design, is there any other place where this could be instead? Some place that is actively called by the broadcaster somehow after starting or saving the recording to S3, idk.

**Comment by darkdarkdragon** [comment]
@victorges 
> That said, I think what this function actually does is something like addRecordingFields instead? Not sure if I misunderstood something or missed some other place where this function is called.

You right, `recordingStatus` is a computed field, and it is computed only when user gets stream object.
Way to do `recording.ready` webhook is:
1. In /setactive, when it's called with active == false, if recording is true - emit delayed `recording.ready` event with delay set to `USER_SESSION_TIMEOUT`
2. In webhook cannon pull this session object and ran `setRecordingStatus` on it - and if it is ready only then fire actual webhook (I think payload for this hook should contain session id and `recordingUrl` and `mp4Url` fields).


P.S.
`recording.started` - is just `stream.started` for streams with `recording` on

**Review by victorges — APPROVED** [review]
LGTM!

**Comment by darkdarkdragon** [comment]
@ya7ya @victorges this will not work - recording __could__ be ready after stream ended, but it is not necessarily so.  In webhook cannon there should be check added (call to `setRecordingStatus`)

**Comment by victorges** [comment]
@darkdarkdragon But doesn't the `setRecordingStatus` just check if the time has passed anyway? Do you mean that the stream/session could become active again and because of that the recording url wouldn't be injected in the stream object? (`lastActive` updated to sth later than `eventTime+5 minutes`)

**Comment by darkdarkdragon** [comment]
@victorges 
>  Do you mean that the stream/session could become active again and because of that the recording url wouldn't be injected in the stream object? 

exactly

**Pull request merged**
