### PR TITLE
Initial api reference commit

### PR DESCRIPTION
**Pull request by wohlner**
This creates an api reference on livepeer.com and adds all the reference copy. And API reference menu item should be at the top of the /docs part of the site.

I think everything is formatted right, and I didn't break anything. But it would be good for an engineer to make sure.

### CODE REVIEW

**Comment by wohlner** [comment]
One "bug" that exists on the guides section and now also exists on the API reference is that you can't access what's in the sidebar menu on mobile. I don't know how to fix this myself. 
Screenshot_20201204-185855

**Comment by adamsoffer** [comment]
> One "bug" that exists on the guides section and now also exists on the API reference is that you can't access what's in the sidebar menu on mobile. I don't know how to fix this myself.

ah yeah there used to be a dropdown in the header on mobile. It might be commented out. I'll fix.

**Comment by adamsoffer** [comment]
@wohlner I've fixed the mobile situation. That can be reviewed now 👍

**Comment by wohlner** [comment]
@adamsoffer Looks like the caret dropdown loads the /docs menu (just api, guides) instead of each sections' menu...the all the pages in guides and all the pages in api reference. The dropdown should have everything in the sidebar on desktop

Also, can you please make the upside down caret purple and/or bold to help draw the eye to it.

**Comment by adamsoffer** [comment]
@wohlner can you do a hard refresh? You should see a dropdown with all the pages in the side bar.

image

**Comment by adamsoffer** [comment]
> Also, can you please make the upside down caret purple and/or bold to help draw the eye to it.

@wohlner I pushed up a change that makes the carrot bigger and more bold to draw more attention to it.

**Comment by wohlner** [comment]
Looks great, @adamsoffer. Can you remove the caret next to the logo? It repeats what is in the hamburger menu. That is what i was looking at with my previous comment and it got me confused.
Screen Shot 2020-12-08 at 4 49 16 PM

**Comment by adamsoffer** [comment]
> Can you remove the caret next to the logo?

@wohlner All set

**Comment by wohlner** [comment]
@adamsoffer let's get this deployed to production (stage first of course). Everything looks great!

**Review by adamsoffer — APPROVED** [review]
Looks great!

**Pull request merged**
